// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RochelleServer;

namespace RochelleServer.Migrations
{
    [DbContext(typeof(RochelleDbContext))]
    [Migration("20181231015030_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("RochelleShared.Models.Company", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DeletedDate");

                    b.Property<string>("DeletedUser");

                    b.Property<string>("InsertedDate");

                    b.Property<string>("InsertedUser");

                    b.Property<string>("Name");

                    b.Property<string>("UpdatedDate");

                    b.Property<string>("UpdatedUser");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("RochelleShared.Models.Customer", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("BirthDate");

                    b.Property<string>("CompanyId");

                    b.Property<string>("DeletedDate");

                    b.Property<string>("DeletedUser");

                    b.Property<string>("Document");

                    b.Property<string>("Email");

                    b.Property<string>("InsertedDate");

                    b.Property<string>("InsertedUser");

                    b.Property<string>("Name");

                    b.Property<string>("UpdatedDate");

                    b.Property<string>("UpdatedUser");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("RochelleShared.Models.Invite", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<string>("CompanyId");

                    b.Property<string>("CustomerFromId");

                    b.Property<string>("CustomerToId");

                    b.Property<string>("DeletedDate");

                    b.Property<string>("DeletedUser");

                    b.Property<DateTime>("ExpirationDate");

                    b.Property<string>("InsertedDate");

                    b.Property<string>("InsertedUser");

                    b.Property<int>("InviteStatus");

                    b.Property<string>("UpdatedDate");

                    b.Property<string>("UpdatedUser");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CustomerFromId");

                    b.HasIndex("CustomerToId");

                    b.ToTable("Invites");
                });

            modelBuilder.Entity("RochelleShared.Models.Login", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CompanyId");

                    b.Property<string>("CustomerId");

                    b.Property<string>("DeletedDate");

                    b.Property<string>("DeletedUser");

                    b.Property<string>("Email");

                    b.Property<string>("FullName");

                    b.Property<string>("InsertedDate");

                    b.Property<string>("InsertedUser");

                    b.Property<string>("Password");

                    b.Property<int>("State");

                    b.Property<string>("UpdatedDate");

                    b.Property<string>("UpdatedUser");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Logins");
                });

            modelBuilder.Entity("RochelleShared.Models.ParamConfiguration", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CompanyId");

                    b.Property<string>("DeletedDate");

                    b.Property<string>("DeletedUser");

                    b.Property<string>("Description");

                    b.Property<string>("InsertedDate");

                    b.Property<string>("InsertedUser");

                    b.Property<string>("Name");

                    b.Property<int>("Type");

                    b.Property<string>("UpdatedDate");

                    b.Property<string>("UpdatedUser");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("ParamConfigurations");
                });

            modelBuilder.Entity("RochelleShared.Models.PointExtract", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CompanyId");

                    b.Property<string>("CustomerId");

                    b.Property<DateTime>("Date");

                    b.Property<string>("DeletedDate");

                    b.Property<string>("DeletedUser");

                    b.Property<string>("Document");

                    b.Property<DateTime?>("Expiration");

                    b.Property<string>("History");

                    b.Property<string>("InsertedDate");

                    b.Property<string>("InsertedUser");

                    b.Property<int>("PointExtractType");

                    b.Property<string>("UpdatedDate");

                    b.Property<string>("UpdatedUser");

                    b.Property<double>("Value");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CustomerId");

                    b.ToTable("PointExtracts");
                });

            modelBuilder.Entity("RochelleShared.Models.PointRule", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CompanyId");

                    b.Property<string>("DeletedDate");

                    b.Property<string>("DeletedUser");

                    b.Property<string>("InsertedDate");

                    b.Property<string>("InsertedUser");

                    b.Property<string>("Name");

                    b.Property<int>("PointRuleType");

                    b.Property<double>("PointToGain");

                    b.Property<int>("RegisterState");

                    b.Property<string>("UpdatedDate");

                    b.Property<string>("UpdatedUser");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("PointRules");
                });

            modelBuilder.Entity("RochelleShared.Models.Product", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CompanyId");

                    b.Property<string>("DeletedDate");

                    b.Property<string>("DeletedUser");

                    b.Property<string>("InsertedDate");

                    b.Property<string>("InsertedUser");

                    b.Property<string>("Name");

                    b.Property<int>("ProductType");

                    b.Property<int>("RegisterState");

                    b.Property<string>("UpdatedDate");

                    b.Property<string>("UpdatedUser");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("RochelleShared.Models.StoreOrder", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CompanyId");

                    b.Property<string>("CustomerFromId");

                    b.Property<DateTime>("Date");

                    b.Property<string>("DeletedDate");

                    b.Property<string>("DeletedUser");

                    b.Property<string>("InsertedDate");

                    b.Property<string>("InsertedUser");

                    b.Property<string>("StoreOrderStatusId");

                    b.Property<string>("UpdatedDate");

                    b.Property<string>("UpdatedUser");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CustomerFromId");

                    b.HasIndex("StoreOrderStatusId");

                    b.ToTable("StoreOrders");
                });

            modelBuilder.Entity("RochelleShared.Models.StoreOrderItem", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CompanyId");

                    b.Property<string>("DeletedDate");

                    b.Property<string>("DeletedUser");

                    b.Property<string>("InsertedDate");

                    b.Property<string>("InsertedUser");

                    b.Property<string>("ProductId");

                    b.Property<double>("Quantity");

                    b.Property<string>("StoreOrderId");

                    b.Property<string>("UpdatedDate");

                    b.Property<string>("UpdatedUser");

                    b.Property<double>("ValuePoint");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ProductId");

                    b.HasIndex("StoreOrderId");

                    b.ToTable("StoreOrderItems");
                });

            modelBuilder.Entity("RochelleShared.Models.StoreOrderStatus", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DeletedDate");

                    b.Property<string>("DeletedUser");

                    b.Property<string>("Description");

                    b.Property<string>("InsertedDate");

                    b.Property<string>("InsertedUser");

                    b.Property<string>("Name");

                    b.Property<int>("Sequence");

                    b.Property<string>("UpdatedDate");

                    b.Property<string>("UpdatedUser");

                    b.HasKey("Id");

                    b.ToTable("StoreOrderStatus");
                });

            modelBuilder.Entity("RochelleShared.Models.StoreProduct", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CompanyId");

                    b.Property<string>("DeletedDate");

                    b.Property<string>("DeletedUser");

                    b.Property<string>("InsertedDate");

                    b.Property<string>("InsertedUser");

                    b.Property<string>("ProductId");

                    b.Property<int>("RegisterState");

                    b.Property<string>("UpdatedDate");

                    b.Property<string>("UpdatedUser");

                    b.Property<double>("ValuePoint");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ProductId");

                    b.ToTable("StoreProducts");
                });

            modelBuilder.Entity("RochelleShared.Models.Customer", b =>
                {
                    b.HasOne("RochelleShared.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");
                });

            modelBuilder.Entity("RochelleShared.Models.Invite", b =>
                {
                    b.HasOne("RochelleShared.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.HasOne("RochelleShared.Models.Customer", "CustomerFrom")
                        .WithMany()
                        .HasForeignKey("CustomerFromId");

                    b.HasOne("RochelleShared.Models.Customer", "CustomerTo")
                        .WithMany()
                        .HasForeignKey("CustomerToId");
                });

            modelBuilder.Entity("RochelleShared.Models.Login", b =>
                {
                    b.HasOne("RochelleShared.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.HasOne("RochelleShared.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");
                });

            modelBuilder.Entity("RochelleShared.Models.ParamConfiguration", b =>
                {
                    b.HasOne("RochelleShared.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");
                });

            modelBuilder.Entity("RochelleShared.Models.PointExtract", b =>
                {
                    b.HasOne("RochelleShared.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.HasOne("RochelleShared.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");
                });

            modelBuilder.Entity("RochelleShared.Models.PointRule", b =>
                {
                    b.HasOne("RochelleShared.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");
                });

            modelBuilder.Entity("RochelleShared.Models.Product", b =>
                {
                    b.HasOne("RochelleShared.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");
                });

            modelBuilder.Entity("RochelleShared.Models.StoreOrder", b =>
                {
                    b.HasOne("RochelleShared.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.HasOne("RochelleShared.Models.Customer", "CustomerFrom")
                        .WithMany()
                        .HasForeignKey("CustomerFromId");

                    b.HasOne("RochelleShared.Models.StoreOrderStatus", "StoreOrderStatus")
                        .WithMany()
                        .HasForeignKey("StoreOrderStatusId");
                });

            modelBuilder.Entity("RochelleShared.Models.StoreOrderItem", b =>
                {
                    b.HasOne("RochelleShared.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.HasOne("RochelleShared.Models.StoreProduct", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.HasOne("RochelleShared.Models.StoreOrder")
                        .WithMany("Items")
                        .HasForeignKey("StoreOrderId");
                });

            modelBuilder.Entity("RochelleShared.Models.StoreProduct", b =>
                {
                    b.HasOne("RochelleShared.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.HasOne("RochelleShared.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");
                });
#pragma warning restore 612, 618
        }
    }
}
